초기환경세팅
wecode-bootcamp-korea/39-1st-PickEat-backend pull request #1
Opened 2022-11-15 01:56 UTC by hosose

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- backend 초기 환경 세팅

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. .gitignore 에 다음의 자동생성 사이트를 이용하여 vim, macOS, node, linux, visualStudioCode, dotenv 등 포함

2. .gitignore 에 dbmate(schema.sql) 파일과 추후 생성하고 관리할 csv 파일 확장자명/디렉토리 포함.

3. 필요한 package 설치

4. package.json ”script” 상 세부내역 수정

5. .env 실제 런서버 구동이 올바르게 이루어지는 환경변수 작성

6. 상기 .env 파일에 기반한 .env.sample 파일 작성

7. app.js 파일 생성 및 내부에 필요 코드(패키지 require 문, Health Check 문 등) 작성

8. ERD 설계 완료

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- 초기환경 세팅을 복습하면서 기존에 사용했던 모듈들을 다시 상기할 수 있었습니다.(블로그 작성 必)

<br />

## :: 기타 질문 및 특이 사항

2022-11-15 02:11 UTC, hosose commented
![image](https://user-images.githubusercontent.com/112751572/201809435-87f1d80c-bcc5-4385-a07f-23a80fdc892d.png)


ERD 완료하였습니다.

2022-11-15 08:52 UTC, bigfanoftim requested changes

2022-11-15 08:52 UTC, bigfanoftim commented on csv_file/lecture.csv
> +id,lecture_categoryId,lecture_title,lecture_content,lecture_ImgUrl,lecture_price,lecture_commentId
csv 파일도 github에는 올라올 필요가 없으니 gitignore 에 추가해서 관리해 주세요~

2022-11-15 08:52 UTC, bigfanoftim commented on pull_request_template.md
>  ## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
template은 말그대로 template입니다! 해당 내용은 그대로 두신 후 PR올리실 때 그에 맞게 description을 수정하시면 됩니다 ㅎㅎ

2022-11-15 12:12 UTC, hosose commented
![image](https://user-images.githubusercontent.com/112751572/201916667-7f708722-a35a-4302-b18e-c32a6e2a0451.png)

호준님 order_status 와 order_item_status 테이블을 나눈 이유가 궁금합니다! 분명 들었는데 기억을 하지 못하였습니다.
저희가 생각하는 것은 배송 상태는 배송 준비중, 배송 중, 취소, 배송 완료 이렇게 중복될 것 같은데 혹시 금일 이야기해주신 내용 기억하신다면 답변 부탁드립니다.

2022-11-16 01:06 UTC, bigfanoftim commented
주문에 대한 상태(order_status) : `주문 취소, 주문 대기, 주문 완료`
주문 상품에 대한 상태(order_item_status) : 상품 개별에 대한 상태..

라고 볼 수 있겠네요~!

2022-11-16 01:13 UTC, bigfanoftim requested changes

2022-11-16 01:13 UTC, bigfanoftim commented on dataSource.js
> +const { DataSource } = require("typeorm");
`data-source.js` 는 `/models/`에 위치시켜 주세요!

2022-11-16 01:13 UTC, bigfanoftim commented on db/migrations/20221115081336_create_users_table.sql
> +    CONSTRAINT PHONE_NUMBER_UNIQUE UNIQUE (phone_number)
전화번호는 unique를 안걸어주는 것이 좋아보입니다. 누군가 회원가입 시 등록했던 전화번호를 더 이상 사용하지 않는데 새로운 사람이 그 전화번호를 가지고 회원가입을 하려고 한다면 문제가 될 것 같아요. 엄청 흔하지 않은 케이스겠지만 충분히 발생할 수 있는 일이라고 보여집니다.

2022-11-16 01:13 UTC, bigfanoftim commented on db/migrations/20221115082146_create_products_table.sql
> +    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`updated_at`은 전부 NULL로 설정하는 것이 좋아보입니다~ 물론 NULL이 아니어도 로직으로 충분히 해결할 수 있겠지만 굳이? 라는 생각이 드네요.

2022-11-16 01:13 UTC, bigfanoftim commented on db/migrations/20221115082210_create_product_images_table.sql
> +    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
이미지의 이력관리가 과연 필요할까 라는 생각이 듭니다.

2022-11-16 01:13 UTC, bigfanoftim commented on db/migrations/20221115082338_create_comments_table.sql
> +    rate decimal NOT NULL,
`DECIMAL`의 경우 어떤 식으로 저장할지 정확히 작성하는 것이 중요합니다.

예) `rate decimal(2,1) NOT NULL`

2022-11-16 01:13 UTC, bigfanoftim commented on db/migrations/20221115082146_create_products_table.sql
> +    category_id INT NOT NULL,
price가 보이지 않네요~

2022-11-16 01:21 UTC, hosose commented on dataSource.js
> +const { DataSource } = require("typeorm");
네. 알겠습니다.

2022-11-16 01:21 UTC, hosose commented on db/migrations/20221115081336_create_users_table.sql
> +    CONSTRAINT PHONE_NUMBER_UNIQUE UNIQUE (phone_number)
네 확인했습니다.

2022-11-16 01:25 UTC, hosose commented on db/migrations/20221115082338_create_comments_table.sql
> +    rate decimal NOT NULL,
네 확인하였습니다.

2022-11-16 01:26 UTC, hosose commented on db/migrations/20221115082210_create_product_images_table.sql
> +    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
호준님의 말씀대로 이미지의 이력관리는 필요하지 않을 것 같습니다.

2022-11-16 01:28 UTC, hosose commented on db/migrations/20221115082338_create_comments_table.sql
> +    rate decimal NOT NULL,
또한 DECIMAL 의 사용 방법을 완벽히 이해했습니다.
예를 들어, 99.99 를 표현하고 싶으면 DECIMAL(4,2)를 작성하면 됩니다.

2022-11-16 01:28 UTC, hosose commented on db/migrations/20221115082146_create_products_table.sql
> +    category_id INT NOT NULL,
깜빡했습니다. ㅎㅎ 수정하였습니다.

2022-11-16 01:30 UTC, hosose commented on db/migrations/20221115082146_create_products_table.sql
> +    category_id INT NOT NULL,
price는 varchar로 작성하였습니다. 숫자를 counting 할 때, ',' 를 사용하여 단위를 보기 쉽게 하기 때문에 varchar로 작성했습니다.
예를 들어, 400,000원 이렇게 표현되기 때문입니다.

2022-11-16 01:30 UTC, hosose commented on db/migrations/20221115082146_create_products_table.sql
> +    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
네 확인했습니다.

2022-11-16 01:52 UTC, hosose commented
호준님! 리뷰 반영하여 내용 수정하였습니다. API 만드는 중간에 진행해가지고 lecture 관련 API 가 추가되었는데 괜찮을까요?

또 하나 질문 사항이 있는데, 11월 15일 밤에 웹 페이지와 서버 연결을 시도하였는데 response 값이 받아지지 않아서 연동을 하지 못하였습니다. response를 통해 분명히 보내준 것 같은데 개발자 도구창에서 response를 확인하지 못하였습니다.
이 문제에 대해 시간이 있으시다면 도움 부탁드립니다.

친절한 리뷰 감사합니다!

2022-11-16 06:01 UTC, hosose commented
호준님 연동은 완료하였습니다. 감사합니다.

2022-11-16 08:46 UTC, bigfanoftim commented on db/migrations/20221115082146_create_products_table.sql
> +    category_id INT NOT NULL,
> price는 varchar로 작성하였습니다. 숫자를 counting 할 때, ',' 를 사용하여 단위를 보기 쉽게 하기 때문에 varchar로 작성했습니다.
예를 들어, 400,000원 이렇게 표현되기 때문입니다.

`,를 이용하여 숫자를 보여주는 것`은 프론트엔드가 처리해서 보여줄 문제고 실제로 데이터가 숫자로 관리가 되어야 하는 것을 굳이 데이터베이스에서 부터 string으로 바꿀 필요는 전혀 없습니다.

2022-11-16 08:47 UTC, bigfanoftim commented
> 호준님! 리뷰 반영하여 내용 수정하였습니다. API 만드는 중간에 진행해가지고 lecture 관련 API 가 추가되었는데 괜찮을까요?

PR에는 하나의 기능만 담는다고 생각하시면 됩니다!

다른 기능이 추가되었다면 해당 기능은 지우시고 다시 푸시해 주세요!

2022-11-16 09:36 UTC, hosose commented
새로 추가한 기능들은 제거하고 올렸습니다!

2022-11-16 09:36 UTC, hosose commented on db/migrations/20221115082146_create_products_table.sql
> +    category_id INT NOT NULL,
네 알겠습니다. 확인했습니다.

2022-11-17 02:09 UTC, bigfanoftim requested changes
PR내 Files changed 꼭 확인해 주세요!

2022-11-17 02:09 UTC, bigfanoftim commented on services/lectureService.js
> +module.exports = { getAllLecture };
👀

2022-11-17 02:26 UTC, hosose commented
앗... 꼼꼼하게 확인하지 못하였습니다 ㅠ

2022-11-17 05:00 UTC, bigfanoftim approved these changes

2022-11-17 05:01 UTC, merged