feature/commentAPI(1)
wecode-bootcamp-korea/39-1st-PickEat-backend pull request #11
Opened 2022-11-23 07:45 UTC by devdev2022

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 댓글 기능을 추가하였습니다. 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

- 로그인 토큰을 받아와 로그인한 사람만 댓글을 쓸 수 있도록 만들었습니다. 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- 레이어드 패턴과 API작성에 대한 전반적인 이해를 높였습니다. 
- 
<br />

## :: 기타 질문 및 특이 사항

2022-11-23 07:52 UTC, bigfanoftim commented on routes/commentRouter.js
> +router.post("/:productid", loginRequired, commentController.createComment);
```JavaScript
// 👍 
POST :3000/comment/productId/1

// 💩 - comment id 1을 post하는 것처럼 느껴집니다.
POST :3000/comment/1
```
productId 1번의 데이터를 요청하는 API의 주소를 `:3000/products/1`로 작성하는 예를 생각해보면 와닿으실겁니다.

2022-11-23 07:59 UTC, bigfanoftim requested changes

2022-11-23 07:59 UTC, bigfanoftim commented on controllers/commentController.js
> +  const productId = req.params.productid;
```suggestion
  const productId = req.params.productId;
```

2022-11-23 07:59 UTC, bigfanoftim commented on routes/commentRouter.js
> +router.post("/:productid", loginRequired, commentController.createComment);
추가로 생각해볼만한점은 어차피 POST로 작성하기 때문에 팀의 의사결정에 따라 body에 모든 정보를 보내는 경우도 있을 수 있겠습니다.
```JavaScript
POST :3000/comments

Body: ..
```

2022-11-23 07:59 UTC, bigfanoftim commented on controllers/commentController.js
> +    message: "create_comment_success",
```suggestion
    message: "SUCCESS",
```
위에서 `KEY_ERROR`라고 작성하셨으니 그 형식에 맞게 아래도 작성해 주세요.
모든 통일된 하나의 방식으로 관리하는 것이 도움이 됩니다.

2022-11-24 06:57 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-24 11:37 UTC, devdev2022 commented
Git conflict 해결완료했습니다!

2022-11-24 11:38 UTC, merged