Feature/lecture api
wecode-bootcamp-korea/39-1st-PickEat-backend pull request #2
Opened 2022-11-16 07:46 UTC by hosose

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 강의(lecture) 관련 내용 불러오기

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 강의 전체 데이터 불러오기
 - 웹페이지와 연동 성공
2. 특정 강의 상세 페이지 데이터 불러오기
 - 파라미터 값 사용
 - advanced query문 사용
3. 카테고리별 상세 페이지 불러오기
 - 파라미터 값 사용
 - 구현 중...
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 새로운 advanced query 문 학습
- 웹페이지와 연동 시 response의 key값 동일화 학습 (프로트엔드, 백엔드)

<br />

## :: 기타 질문 및 특이 사항

2022-11-16 08:02 UTC, hosose commented
3번까지 API 작성 완료했습니다.

2022-11-16 14:58 UTC, hosose commented
호준님, 댓글 추가 기능을 작성해보면서 궁금한 점이 생겼습니다. lecture_id 를 request로 불러올 때, 
미리 불러왔던 강의의 아이디를 불러올 수 있는 것인지, 아니면 엔드포인트 작성 시 parameter 값을 지정해 줘야하는지 궁금합니다.

예를 들어, 인스타그램의 피드마다 id 값이 있는데 피드의 아이디 값을 불러와서 comment database에 저장을 해야하는지
댓글 추가기능 자체에 피드의 id 값을 지정해서 database에 저장해야하는지 궁금합니다.

2022-11-17 02:26 UTC, bigfanoftim commented
> 호준님, 댓글 추가 기능을 작성해보면서 궁금한 점이 생겼습니다. lecture_id 를 request로 불러올 때, 미리 불러왔던 강의의 아이디를 불러올 수 있는 것인지, 아니면 엔드포인트 작성 시 parameter 값을 지정해 줘야하는지 궁금합니다.
> 
> 예를 들어, 인스타그램의 피드마다 id 값이 있는데 피드의 아이디 값을 불러와서 comment database에 저장을 해야하는지 댓글 추가기능 자체에 피드의 id 값을 지정해서 database에 저장해야하는지 궁금합니다.

댓글을 남기는 해당 피드의 id를 저장해야 관계가 성립됩니다. 아무 id나 갑자기 지정해서 저장하면 아무런 의미가 없습니다.

2022-11-17 02:29 UTC, bigfanoftim requested changes

2022-11-17 02:29 UTC, bigfanoftim commented on controllers/lectureController.js
> +};
1. lectureId를 가지고 lecture를 하나만 불러오는 API
2. 여러 parameter를 받아와 필터링 후 lecture 여러개를 불러오는 API

다음과 같이 2개의 엔드포인트만 존재하면 됩니다. category말고 다른 필터링 방법이 생긴다고 해서 엔드포인트가 여러개가 생성되게 되면 필터링 조건이 5개만 되어도 엔드포인트는 수십개가 존재하게 됩니다.

2022-11-17 02:29 UTC, bigfanoftim commented on controllers/lectureController.js
> +};
이건 아예 다른 기능이니 PR을 분리해 주세요.

2022-11-17 02:29 UTC, bigfanoftim commented on controllers/lectureController.js
> +};
따라서 1번과 2번의 기능은 서로 다른 기능이니 PR을 분리해 주세요.

2022-11-17 07:07 UTC, hosose commented
일단 lecture id 로 특정 lecture 가져오는 path parameter를 이용한 api 만 남겨놓았고 , 다른 기능은 다음 브랜치에 만들겠습니다.

궁금한 점이 있습니다. 또 다시 이 기능에 대한 수정사항이 발생할 수 있으니 merge는 다음에 하나요? 그게 맞겠죠?

2022-11-17 07:40 UTC, bigfanoftim commented
> 일단 lecture id 로 특정 lecture 가져오는 path parameter를 이용한 api 만 남겨놓았고 , 다른 기능은 다음 브랜치에 만들겠습니다.
> 궁금한 점이 있습니다. 또 다시 이 기능에 대한 수정사항이 발생할 수 있으니 merge는 다음에 하나요? 그게 맞겠죠?

수정사항이라면 어떤 수정사항일까요? 애초에 완료된 기능은 머지 후 유지 보수는 다시 새로운 PR에서 진행하면 됩니다.

2022-11-17 08:44 UTC, hosose commented
> > 일단 lecture id 로 특정 lecture 가져오는 path parameter를 이용한 api 만 남겨놓았고 , 다른 기능은 다음 브랜치에 만들겠습니다.
> > 궁금한 점이 있습니다. 또 다시 이 기능에 대한 수정사항이 발생할 수 있으니 merge는 다음에 하나요? 그게 맞겠죠?
> 
> 수정사항이라면 어떤 수정사항일까요? 애초에 완료된 기능은 머지 후 유지 보수는 다시 새로운 PR에서 진행하면 됩니다.

앗! 그렇게 하면 되는거군요! 감사합니다.

2022-11-17 09:06 UTC, hosose commented
conflict 해결하였는데... 잘 된거겠죠 ㅎㅎ

2022-11-18 03:12 UTC, bigfanoftim requested changes

2022-11-18 03:12 UTC, bigfanoftim commented on controllers/lectureController.js
> +    return res.status(201).json(lectures);
```suggestion
```
201은 어울리지 않아보이네요!

2022-11-18 03:12 UTC, bigfanoftim commented on models/lectureDao.js
> +    WHERE P.id = ?
indent가 알아보기 힘드네요..ㅠ 들여쓰기 다시 확인해 주세요!

2022-11-18 09:06 UTC, hosose commented on models/lectureDao.js
> +    WHERE P.id = ?
괄호가 많을 때는 어떻게 정리하는지 감은 안왔지만 최대한 정리해봤습니다. 다른 branch에서도 해보겠습니다.

2022-11-18 09:19 UTC, hosose commented on controllers/lectureController.js
> +    return res.status(201).json(lectures);
응답코드 200이 맞다고 생각합니다.

200 OK : 요청이 성공적으로 되었습니다. 정보는 요청에 따른 응답으로 반환됩니다.
라는 뜻입니다.

2022-11-21 01:37 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-21 01:37 UTC, merged