Feature/get products by query parm
wecode-bootcamp-korea/39-1st-PickEat-backend pull request #3
Opened 2022-11-17 14:15 UTC by hosose

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- query parameter 로 강의, 재료, 책 등의 여러 타입의 product를 불러오는 API 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. query parameter 엔드포인트
-  "/products?name='카테고리 이름'&type='제품이름'" 하나의 API로 강의, 책, 재료 페이지를 분류할 수 있습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- query parameter를 사용해서 request 값으로 불러오기 학습

<br />

## :: 기타 질문 및 특이 사항

- 제가 생각하기에 products 테이블 안에 강의 , 책, 재료 가 있기 때문에 하나의 API 로 카테고리별 분류를 할 수 있다고 생각해서 query parameter 로 접근하였습니다. 이렇게 하는 것이 맞을까요?

2022-11-18 04:38 UTC, bigfanoftim requested changes

2022-11-18 04:38 UTC, bigfanoftim commented on controllers/productController.js
> +    const type = req.query.type;
```suggestion
    const { name, type }  = req.query;
```
이렇게 작성할 수 있습니다!

2022-11-18 04:38 UTC, bigfanoftim commented on models/productDao.js
> +          price,
P. 이 다 붙어야 될 것 같은데요~?

2022-11-18 04:38 UTC, bigfanoftim commented on routes/index.js
>  // const userRouter = require("./userRouter");
불필요한 주석들은 다 지워주세요~

2022-11-18 12:48 UTC, hosose commented on models/productDao.js
> +          price,
앗! 중복되는 값이 없어서 작동되길래 빼버렸는데, 다음부터는 넣도록 하겠습니다!

2022-11-18 12:48 UTC, hosose commented on routes/index.js
>  // const userRouter = require("./userRouter");
네. 확인했습니다.

2022-11-21 02:37 UTC, hosose commented
호준님 지금 merge된 내용을 변경하고 싶을 때는 작업했던 branch에서 다시 pull & request를 해줘야하는 것일까요?

2022-11-21 07:00 UTC, bigfanoftim commented
> 호준님 merge된 내용을 변경하고 싶을 때는 작업했던 branch에서 다시 pull & request를 해줘야하는 것일까요?

머지된 내용을 가지고 있는 브랜치기만 하면 상관없습니다.

2022-11-21 11:57 UTC, hosose commented
로그인 , 회원가입 api에서 문제가 생겨서 아직 merge를 기다려야겠습니다. 내일 한솔님께서 호준님과 이야기를 할 예정입니다!

2022-11-23 05:10 UTC, bigfanoftim commented
> 로그인 , 회원가입 api에서 문제가 생겨서 아직 merge를 기다려야겠습니다. 내일 한솔님께서 호준님과 이야기를 할 예정입니다!

해당 PR은 로그인, 회원가입과 전혀 관계가 없는데 굳이 기다릴 필요가 있을까 싶네요~ 우선 라벨 지워놓겠습니다.

2022-11-24 02:06 UTC, bigfanoftim commented on routes/productRouter.js
> +router.get("/", productController.getProductsByParameter);
```suggestion
router.get("", productController.getProductsByParameter);
```
뒤에 주소가 더 추가되지 않는다면 `/`는 작성하지 말아주세요~

2022-11-24 02:06 UTC, bigfanoftim commented on controllers/productController.js
> +  return res.status(201).json(products);
```suggestion
  return res.status(200).json(products);
```
`201`은 레코드 생성을 의미합니다. 다른 상태코드로 변경해 주세요~

2022-11-24 06:52 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-24 06:52 UTC, merged