장바구니 추가 API
wecode-bootcamp-korea/39-1st-PickEat-backend pull request #5
Opened 2022-11-19 14:44 UTC by hosose

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 장바구니 추가 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 장바구니 database 추가 기능 구현
- user login 기능으로 token 을 받아 user id 변수값 지정 완료
- product parameter 값으로 product id 변수값 지정 완료
- product 수량 request body 값으로 받아 인자에 추가 완료
2. client request 직접 구현 완료
- 웹페이지에서 장바구니 추가 버튼을 함수로 지정 후 그 함수 속에 fetch값을 넣어 엔드포인트 지정 완료 (장바구니 추가 버튼을 누르면 database에 저장하는 것 확인)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- 웹페이지와 연동하면서 웹 페이지의 fetch 기능 넣는 것 이해
- 요청 시 headers에 token 값을 넣어야하는 것 이해
- product 상세페이지에 불러온 id 값을 usestate에 저장하는 것 이해

<br />

## :: 기타 질문 및 특이 사항

2022-11-19 15:23 UTC, hosose commented
token을 받기 위해서는 유저 signin이라는 api가 필요해서 자바스크립트 파일을 넣었는데... 이것도 merge하는데 방해를 하게 되면 마지막에 빼야겠죠?

2022-11-23 05:24 UTC, bigfanoftim commented
장바구니 관련된 코드만 올라오도록 수정 후 다시 push 해주세요~ 수정하고 싶으신게 있다면 수정하고 싶은 것만 따로 PR로 올려주세요,

2022-11-24 02:33 UTC, bigfanoftim requested changes

2022-11-24 02:33 UTC, bigfanoftim commented on routes/index.js
> +router.use("/lecture", lectureRouter);
👀

2022-11-24 02:33 UTC, bigfanoftim commented on controllers/cartController.js
> +const addProduct = catchAsync(async (req, res) => {
```suggestion
const addProduct = catchAsync(async (req, res) => {
```
`addProduct`는 상품 자체를 추가하는 의미를 가지는 것 같습니다. 장바구니 데이터를 생성하는 의미의(`addCart`) 네이밍이 필요할 것 같아요.

2022-11-24 02:33 UTC, bigfanoftim commented on controllers/cartController.js
> +  const userId = user.id;
`user` 변수는 선언할 필요가 없어보이네요.
```suggestion
  const userId = req.user.id;
```

2022-11-24 02:33 UTC, bigfanoftim commented on services/cartService.js
> +  }
이부분은 애초에 값이 들어오지 않았을때 예외처리를 해줘야하는 부분이라고 생각이 드네요.

그렇지 않다 하더라도 parameter에 대해 default를 주는 것이 더 좋을 것 같습니다.

2022-11-24 02:33 UTC, bigfanoftim commented on services/cartService.js
> +  }
cart에 해당 상품이 이미 담겨있다면 `이미 담겨있으니 추가를 못한다` 가 아니라 이미 담겨있는 상품 갯수에 추가된 수량을 더해야 하지 않을까요?

2022-11-24 05:18 UTC, bigfanoftim requested changes

2022-11-24 05:18 UTC, bigfanoftim commented on models/cartDao.js
> +const addCart = async (userId, productId, quantity) => {
```suggestion
const addCart = async (userId, productId, quantity=1) => {
```

2022-11-24 05:18 UTC, bigfanoftim commented on services/cartService.js
> +  const cartProduct = await cartDao.getCartByUserId(userId);
```suggestion
  const carts = await cartDao.getCartByUserId(userId);
```

2022-11-24 05:18 UTC, bigfanoftim commented on models/cartDao.js
> +const getCartByUserId = async (userId) => {
```suggestion
const getCartsByUserId = async (userId) => {
```

2022-11-24 06:52 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-24 06:53 UTC, bigfanoftim commented
conflict 해결 후 직접 머지해보세요 세호님~

2022-11-24 07:44 UTC, hosose commented
> conflict 해결 후 직접 머지해보세요 세호님~

저에게 이런 기회를... 좋습니다.

2022-11-24 07:44 UTC, merged