Feature/get cart by user
wecode-bootcamp-korea/39-1st-PickEat-backend pull request #6
Opened 2022-11-19 15:28 UTC by hosose

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- user ID로 장바구니 페이지 내용 불러오기 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. token을 이용하여 user ID를 가져오고 조건문에 삽입
- login 할 때 user ID를 넣은 token을 받아서 headers에 넣고 query문을 이용하여 배열로 response 완료

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- token을 이용하여 user id 값을 받아오는 것 이해
- 토큰을 로컬스토리지에 받고, 프론트엔드 개발자분이 로컬스토리지에 저장된 토큰을 get item 함수를 이용하여 받아오는 것 이해

<br />

## :: 기타 질문 및 특이 사항

- login 기능이 없으면 token을 받아오기 힘들어서 api를 넣어 놓았는데 merge 시 불필요하다면 빼고 다시 git push 하겠습니다.

2022-11-23 05:31 UTC, bigfanoftim requested changes
이것도 아까와 같은 이유로 한번씩만 살펴봐주세요~

2022-11-24 02:38 UTC, bigfanoftim requested changes

2022-11-24 02:38 UTC, bigfanoftim commented on routes/cartRouter.js
> +router.get("/", loginRequired, cartController.getCartByUserId);
```suggestion
router.get("", loginRequired, cartController.getCartByUserId);
```

2022-11-24 02:38 UTC, bigfanoftim commented on controllers/cartController.js
> +  }
컨트롤러에서 userId가 없는 경우는 사실 존재할 수가 없습니다. 이미 토큰을 검증하는 미들웨어에서 예외 처리하기 때문입니다. 만약 미들웨어에서 해당하는 처리가 안되어 있다면 거기에 추가해 주세요.

추가로 해당 미들웨어를 수정할 계획이시라면 다른 PR로 분리해서 빠르게 적용해주세요.

2022-11-24 02:38 UTC, bigfanoftim commented on controllers/cartController.js
> +  const cart = await cartService.getCartByUserId(userId);
```suggestion
  const carts = await cartService.getCartByUserId(userId);
```
userId로 필터링하면 장바구니가 하나가 아닐 수 있습니다. 정확한 네이밍을 하는 습관을 길러주세요.

2022-11-24 05:01 UTC, hosose commented on routes/cartRouter.js
> +router.get("/", loginRequired, cartController.getCartByUserId);
'엔드포인트가 없을 때는 넣지 말자!' 가슴 속에 새기겠습니다.

2022-11-24 05:02 UTC, hosose commented on controllers/cartController.js
> +  }
미들웨어에 들어있는 것을 또 중복되게 작성하였네요. 수정하겠습니다.

2022-11-24 05:03 UTC, hosose commented on controllers/cartController.js
> +  const cart = await cartService.getCartByUserId(userId);
네! 알겠습니다. 네이밍할 때 구체적인 것까지 생각하겠습니다.

2022-11-24 06:56 UTC, bigfanoftim approved these changes
LGTM 👍 
approve 했으니 conflict 해결 후 직접 머지해보세요~

2022-11-24 07:57 UTC, merged