로그인 api 구현
wecode-bootcamp-korea/39-1st-PickEat-backend pull request #8
Opened 2022-11-22 01:48 UTC by hosose

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 로그인 기능 구현
- bcrypt decoding을 통해 비밀번호 확인
- jsonwebtoken 전송

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- bcrypt 이해
- jsonwebtoken 이해

<br />

## :: 기타 질문 및 특이 사항

- 기존에 merge 된 signin 기능을 삭제하고 지금 pull & request 한 것으로 merge를 하고 싶습니다!

2022-11-22 08:13 UTC, bigfanoftim requested changes
- PR을 올리신 후에는 반드시 PR에 있는 `Files changed` 탭을 눌러 본인이 의도한 방향으로 코드가 잘 작성되었는지 확인해야 합니다.
- PR 올리기 전 각자 사용하고 있는 IDE(Vim, Vscode, WebStrom, IntelliJ 등)에서 Git 변경 사항을 체크하는 것도 좋은 방법입니다.

2022-11-22 08:13 UTC, bigfanoftim commented on routes/userRouter.js
> +router.use("/signin", userController.signIn);
```suggestion
router.post("/signin", userController.signIn);
```

2022-11-22 08:13 UTC, bigfanoftim commented on services/userService.js
> +    throw err;
저희 저번에 custom error raise하는 함수 만들지 않았었나요?

2022-11-22 08:13 UTC, bigfanoftim commented on services/userService.js
> +  return user;
테스트하고 올리신 코드 맞나요?

2022-11-22 08:13 UTC, bigfanoftim commented on services/userService.js
> +};
👀

2022-11-22 09:14 UTC, hosose commented on services/userService.js
> +  return user;
같은 이메일로 회원가입을 할 수도 있기 때문에 회원가입 시 같은 이메일을 등록하려고 하면 에러가 뜨게 만들기 위해 작성했고, 테스트 시 잘 이용됩니다.
하지만 select를 전부 할 필요가 없다면 email 만 select 하게 수정하겠습니다.

2022-11-22 09:19 UTC, hosose commented on services/userService.js
> +};
utils 디렉토리에 있는 checkuser.js 에서 토큰 값에 저장된 id 값으로 user가 있는지 확인하는데 이용되는 것입니다. 
더 좋게 바꿔야 하는 것일까요?

2022-11-22 15:01 UTC, hosose commented on services/userService.js
> +    throw err;
맞습니다! 다시 수정하겠습니다

2022-11-23 02:19 UTC, bigfanoftim commented on services/userService.js
> +};
이번 PR과는 상관없는 코드여서 커멘트 남겼습니다. 지금은 이후에 main merge하시면서 해결된 것으로 보입니다 ㅎㅎ 항상 Files changed 확인해 주세요ㅣ.

2022-11-23 02:22 UTC, bigfanoftim commented on services/userService.js
> +  return user;
해당 코드는 DataSource 객체를 불러와 query 메소드를 활용해야하는 model layer 함수인데도 불구하고 service layer에 있어서 커멘트 남겼습니다. 
저 상태에서 database라는 undefined 객체에 query를 하고 있었는데 테스트가 잘 된다니 아마 해결 이후에 테스트하셨나 봅니다.
PR을 올리고 라벨을 바꾸는 시점에 이미 테스트가 된 상태로 올라와야 합니다.

2022-11-23 02:22 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-23 02:23 UTC, merged

2022-11-23 03:30 UTC, hosose commented on services/userService.js
> +};
네 알겠습니다! 감사합니다!